apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: navidrome-ingress
  namespace: media

spec:
  ingressClassName: nginx
  rules:
    - host: music.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: navidrome-service
              port:
                number: 80

