apiVersion: v1

kind: Service

metadata:
  name: navidrome-service
  namespace: media
  
spec:
  selector:
    app: navi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4533
      nodePort: 30070
  type: NodePort

